<?php

//
// common.inc
//

define('SCC_SERVICE_RDP', 'rdp');
define('SCC_SERVICE_VNC', 'vnc');
define('SCC_SERVICE_HTTP', 'http');
define('SCC_SERVICE_USB_DEVICE', 'usb_device');
define('SCC_SERVICE_DSL', 'dsl');
define('SCC_SERVICE_FILE', 'file');
define('SCC_SERVICE_ZIP', 'zip');
define('SCC_SERVICE_SLIDESHOW', 'slideshow');
define('SCC_SERVICE_MUSIC', 'music');
define('SCC_SERVICE_VIDEO', 'video');
define('SCC_SERVICE_SEARCH_ZIP', 'zip');
define('SCC_SERVICE_SEARCH_SLIDESHOW', 'slideshow');
define('SCC_SERVICE_SEARCH_MUSIC', 'music');
define('SCC_SERVICE_SEARCH_VIDEO', 'video');

define('SHARE_PRIVATE', 0);
define('SHARE_PUBLIC', 1);
define('SHARE_PUBLIC_LINK_ONLY', 2);
